<a href="https://colab.research.google.com/github/24zuli/DeepLearning/blob/main/NN_LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
#!pip install tensorflow

In [116]:
import tensorflow.compat.v1 as tf

In [117]:
print(tf.__version__)

2.18.0


In [118]:
he = tf.constant("Hello")
wo = tf.constant("World")
hewo = he + wo
print(hewo)

Tensor("add_12:0", shape=(), dtype=string)


In [119]:
from os import P_NOWAITO
phe = "Hello"
P_NOWAITO = " World!"
phewo = phe + P_NOWAITO
print(phewo)

Hello World!


In [120]:
tf.disable_eager_execution()


In [121]:
with tf.Session() as sess:
  ans = sess.run(hewo)
print(ans)

b'HelloWorld'


In [122]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)


In [123]:
d = tf.multiply(a,b)
e = tf.add(c,b)
f = tf.subtract(d,e)

In [124]:
sess = tf.Session()
res = sess.run(f)


In [125]:
sess.close()


In [126]:
print(res)

5


In [127]:
print(tf.get_default_graph())

In [128]:
g = tf.Graph()
print(g)

In [129]:
z = tf.constant(8)
print(z.graph is g)

False


In [130]:
print(z.graph is tf.get_default_graph())

True


In [131]:
sess = tf.Session()

In [132]:
fetches = [a,b,c,d,e,f]


In [133]:
res = sess.run(fetches)

In [134]:
sess.close()

In [135]:
print(res)

[5, 2, 3, 10, 5, 5]


In [136]:
a = tf.constant(3)
b = tf.Variable(6)

In [137]:
sum = tf.add(a,b)

In [138]:
sum = a+b

In [139]:
assign_val = tf.assign(b,4)

In [140]:
init_ops = tf.global_variables_initializer()

In [141]:
sess = tf.Session()

In [142]:
sess.run(init_ops)

In [143]:
print(sess.run(sum))

9


In [144]:
sess.run(assign_val)

4

In [145]:
print(sess.run(sum))

7


In [146]:
ph = tf.placeholder(tf.float32)

In [147]:
eqn = ph*2

In [148]:
sess.run(eqn,feed_dict={ph:4.0})

8.0

In [149]:
sess.run(eqn,feed_dict={ph:[1,2,3,4,5]})

array([ 2.,  4.,  6.,  8., 10.], dtype=float32)

In [150]:
sess.run(eqn,feed_dict={ph:[[1,2,3,4,5],[6,7,8,9,8],[7,3,2,1,0]]})

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 16.],
       [14.,  6.,  4.,  2.,  0.]], dtype=float32)

In [151]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [152]:
sum = x+y

In [153]:
prd = sum * 5

In [154]:
sess = tf.Session()

In [155]:
sess.run(prd,feed_dict={x:[3],y:[4]})

array([35.], dtype=float32)